/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Student;
import Connection.Database;
import Statement.Operation;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.sql.*;
import java.util.StringTokenizer;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import net.proteanit.sql.DbUtils;
import other.Hyperlink;
/**
 *
 * @author Adil
 */
public class Student extends javax.swing.JFrame {
JButton[] btn=new JButton[25];
    Connection con;
Statement st;
ResultSet rs;
PreparedStatement pst;
String na,fa,cr,ge,se;
int cl,ro;
boolean table;
/**
     * Creates new form Student
     */
    public Student()  
    {
        
//StringBuffer sb=new StringBuffer();
        //sb.append("<HTML><a href=\"dfoo\">Adil Abdullah</a></HTML>");
        initComponents();
    Database ds=new Database();
        con=ds.Conn();
        //for(int i=0;i<tbl.getRowCount();i++)
        //{
        //tbl.setValueAt("<HTML><a href=\"dfoo\">Edit  Delete</a></HTML>",i, 9);
        //tbl.setValueAt("<HTML><a href=\"dfoo\">Delete</a></HTML>",i, 9);
        //}
        //lbh.setText(Hyperlink("Adil abdullah"));
   // lbh.addHyperlinkListener(new MenuPaneHyperlinkListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        clas = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();
        gr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        day = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        file = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        doa = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(170, 90, 185, 28);

        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        getContentPane().add(clas);
        clas.setBounds(170, 170, 185, 28);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(170, 130, 185, 28);

        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll);
        roll.setBounds(540, 90, 198, 28);

        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });
        getContentPane().add(sec);
        sec.setBounds(170, 210, 185, 28);

        gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grActionPerformed(evt);
            }
        });
        getContentPane().add(gr);
        gr.setBounds(540, 120, 198, 30);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Gender");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 250, 80, 20);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Father Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 110, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Class");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 180, 110, 21);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Section");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 110, 21);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Gr No");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 130, 110, 20);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Date Of Birth");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 170, 120, 20);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setText("Date Of Admission");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 210, 160, 20);

        female.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female);
        female.setBounds(400, 250, 100, 23);

        male.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(300, 250, 100, 29);

        jPanel1.setLayout(null);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 343, 0, 0);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setText("Name");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 70, 82, 21);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(130, 20, 185, 28);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Search");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 82, 21);

        jButton3.setText("Clear");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(539, 430, 80, 29);

        jButton4.setText("Display");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(459, 430, 80, 29);

        jButton5.setText("Clear Table");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(121, 430, 90, 29);

        day.setText("jLabel10");
        day.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayMouseClicked(evt);
            }
        });
        jPanel1.add(day);
        day.setBounds(530, 220, 50, 20);

        month.setText("jLabel10");
        jPanel1.add(month);
        month.setBounds(600, 220, 50, 20);

        year.setText("jLabel14");
        jPanel1.add(year);
        year.setBounds(670, 220, 40, 14);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Father Name", "Class", "Section", "Roll", "Gr", "Date of Birth", "Date of Admission", "age", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
            tbl.getColumnModel().getColumn(2).setResizable(false);
            tbl.getColumnModel().getColumn(3).setResizable(false);
            tbl.getColumnModel().getColumn(4).setResizable(false);
            tbl.getColumnModel().getColumn(5).setResizable(false);
            tbl.getColumnModel().getColumn(6).setResizable(false);
            tbl.getColumnModel().getColumn(7).setResizable(false);
            tbl.getColumnModel().getColumn(8).setResizable(false);
            tbl.getColumnModel().getColumn(9).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 496, 835, 140);

        jButton1.setText("Update");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(389, 430, 70, 29);

        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(303, 430, 80, 29);
        jPanel1.add(path);
        path.setBounds(150, 260, 570, 30);

        file.setText("Attach");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        jPanel1.add(file);
        file.setBounds(30, 260, 120, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Roll");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(379, 70, 110, 20);

        jButton6.setText("Save File");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(619, 430, 80, 29);

        jButton7.setText("Delete");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(51, 51, 255)));
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(221, 430, 80, 29);
        jPanel1.add(dob);
        dob.setBounds(540, 130, 200, 30);
        jPanel1.add(doa);
        doa.setBounds(540, 170, 200, 30);

        jTabbedPane1.addTab("Main", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 840, 750);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(140, 650, 100, 20);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        male.setSelected(false);
        ge=female.getText();
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        female.setSelected(false);
        ge=male.getText();
    }//GEN-LAST:event_maleActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grActionPerformed

    private void dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseClicked
        //day=dob.
    }//GEN-LAST:event_dobMouseClicked

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped

    }//GEN-LAST:event_nameKeyTyped

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        if(table==false)
        try{
            String query="SELECT * FROM info WHERE name='"+name.getText()+"'";
            pst=con.prepareStatement(query);
            rs=pst.executeQuery(query);
            tbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex.getMessage());}
        else{
            try{
                String query="SELECT * FROM info WHERE name='"+name.getText()+"'";
                pst=con.prepareStatement(query);
                rs=pst.executeQuery(query);
                while(rs.next()){
                    tbl.setRowSelectionInterval((int)rs.getInt("Sno")-1,rs.getInt("Sno")-1);
                }}
                catch(Exception ex)
                {ex.printStackTrace();
                    JOptionPane.showMessageDialog(null,ex.getMessage());}

            }
    }//GEN-LAST:event_nameKeyReleased

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed

    }//GEN-LAST:event_nameKeyPressed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        JFileChooser fil=new JFileChooser();
        fil.showOpenDialog(null);
        File file=fil.getSelectedFile();
        String paths=file.getAbsolutePath();
        path.setText(paths);
    }//GEN-LAST:event_fileActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        na=name.getText();
        fa=fname.getText();
        //cl=Integer.parseInt(clas.getText());
        se=sec.getText();
        //ro=Integer.parseInt(roll.getText());
        cr=gr.getText();
        //      if(male.isSelected()==true)
        //      {
            //      female.setSelected(false);
            //      ge=male.getText();
            //      }
        //      else{
            //      male.setSelected(false);
            //      ge=female.getText();
            //      }
        Database dt=new Database();
        Operation op=new Operation();
        try{
            String query="INSERT INTO info(name,father,class,section,roll,gr,dob,doa,gender,path) VALUES (?,?,?,?,?,?,?,?,?,?)";
            //st.executeUpdate(query);
            pst=dt.Conn().prepareStatement(query);
            pst.setString(1, na);
            pst.setString(2, fa);
            pst.setString(3, clas.getText());
            pst.setString(4, se);
            pst.setString(5, roll.getText());
            pst.setString(6, cr);
            pst.setString(7, ((JTextField)dob.getDateEditor().getUiComponent()).getText());
            pst.setString(8, ((JTextField)doa.getDateEditor().getUiComponent()).getText());
            pst.setString(9, ge);
            //  pst.setString(10,op.datediff((dob.getDateEditor().getUiComponent()),(doa.getDateEditor().getUiComponent())));
            pst.setString(10, path.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Saved Successfully");
            rs=op.display(na,"info");
            tbl.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception ex)
        {ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Database dt=new Database();
        Operation opr=new Operation();
        int res=JOptionPane.showConfirmDialog(null,"Do You Really Want To Update","Confirmation",JOptionPane.YES_NO_OPTION);
        if(res==1){
            try{
                String query="UPDATE info (name,father,class,section,roll,gr,dob,doa,gender,path) VALUES(?,?,?,?,?,?,?,?,?,?)";
                pst=dt.Conn().prepareStatement(query);
                pst.setString(1, na);
                pst.setString(2, fa);
                pst.setString(3, clas.getText());
                pst.setString(4, se);
                pst.setString(5, roll.getText());
                pst.setString(6, cr);
                pst.setString(7, ((JTextField)dob.getDateEditor().getUiComponent()).getText());
                pst.setString(8, ((JTextField)doa.getDateEditor().getUiComponent()).getText());
                pst.setString(9,ge);
                pst.setString(10,path.getText());
                pst.execute(); 
                JOptionPane.showMessageDialog(null,"Update Successfully");
                rs=opr.display(na,"info");
                tbl.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }}
            else
            {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseExited
        int sr=tbl.getSelectedRow();
        tbl.setRowSelectionAllowed(true);
        tbl.setCellSelectionEnabled(true);
    }//GEN-LAST:event_tblMouseExited

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // btn[0].setText("Delete");
        int row=tbl.getSelectedRow();
        // tbl.setValueAt(btn[0],row,10);
        String click=tbl.getModel().getValueAt(row,0).toString();
        String value=(tbl.getModel().getValueAt(row, 11).toString());
        try{
            String sql="SELECT * FROM info WHERE name='"+click+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery(sql);
            if(rs.next())
            {
                this.name.setText(rs.getString("name").toString());
                this.fname.setText(rs.getString("father").toString());
                this.clas.setText(rs.getString("class").toString());
                this.sec.setText(rs.getString("section").toString());
                this.doa.setDate(rs.getDate("doa"));
                this.dob.setDate(rs.getDate("dob"));
                this.roll.setText(rs.getString("roll").toString());
                this.gr.setText(rs.getString("gr").toString());
                // if(rs.getString("gender").equalsIgnoreCase("male"))
                //{male.setSelected(true);
                    //female.setSelected(false);}
                //else{female.setSelected(true);
                    //male.setSelected(false);}
            }
        }
        catch(Exception ee)
        {ee.printStackTrace();
            JOptionPane.showMessageDialog(null,ee.getMessage());}
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler"+value);
        }
        catch(Exception ex)
        {JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_tblMouseClicked

    private void dayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayMouseClicked
        day.setForeground(Color.red);
        day.setText("<HTML><a href=\"dfoo\">Karachi</a></HTML>");
    }//GEN-LAST:event_dayMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        for(int i=0;i<tbl.getRowCount();i++)
        {
            for(int j=0;j<tbl.getColumnCount();j++)
            {
                tbl.setValueAt("", i, j);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            String query="SELECT * FROM info";
            pst=con.prepareStatement(query);
            rs=pst.executeQuery(query);
            tbl.setModel(DbUtils.resultSetToTableModel(rs));
            table=true;
        }
        catch(Exception ex)
        {ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        name.setText("");
        fname.setText("");
        clas.setText("");
        sec.setText("");
        gr.setText("");
        roll.setText("");
        dob.setDate(null);
        doa.setDate(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyTyped

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased

        //String sea=search.getText();
//        try{
//            String query="SELECT * FROM info WHERE Sno= ?";
//            pst=con.prepareStatement(query);
//            pst.setString(1, search.getText());
//            rs=pst.executeQuery(query);
//            if(rs.next())
//            {
//                name.setText(rs.getString("name").toString());
//                fname.setText(rs.getString("father").toString());
//                clas.setText(rs.getString("class"));
//                sec.setText(rs.getString("section"));
//                //        try{
//                    //        String sqls="SELECT * FROM info WHERE name= ?";
//                    //        pst=con.prepareStatement(sqls);
//                    //        pst.setString(1, name.getText());
//                    //        rs=pst.executeQuery(sqls);
//                    //        tbl.setModel(DbUtils.resultSetToTableModel(rs));
//                    //        }
//                //        catch(Exception ex)
//                //        {
//                    //        JOptionPane.showMessageDialog(null,ex.getMessage());
//                    //        }
//                //        }
//        }
//        }
        //name.setText(rs.getString("name"));
        //tbl.setModel(DbUtils.resultSetToTableModel(rs));

//        catch(Exception ex)
//        {
//            JOptionPane.showMessageDialog(null,ex.getMessage());
//        }
                try{
                    String query="SELECT * FROM info WHERE name= ?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, search.getText());
                    rs=pst.executeQuery(query);
                    tbl.setModel(DbUtils.resultSetToTableModel(rs));
                if(rs.next())
                {
                
                
                }
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                try{
                    String query="SELECT * FROM info WHERE section= ?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, search.getText());
                    rs=pst.executeQuery(query);
                    tbl.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                try{
                    String query="SELECT * FROM info WHERE father= ?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, search.getText());
                    rs=pst.executeQuery(query);
                    tbl.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                try{
                    String query="SELECT * FROM info WHERE class= ?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, search.getText());
                    rs=pst.executeQuery(query);
                    tbl.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                try{
                    String query="SELECT * FROM info WHERE gender= ?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, search.getText());
                    rs=pst.executeQuery(query);
                    tbl.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                try{
                    String query="SELECT * FROM info WHERE gr= ?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, search.getText());
                    rs=pst.executeQuery(query);
                    tbl.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
    }//GEN-LAST:event_searchKeyReleased

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyPressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       String nam=name.getText();
        try{
       String query="DELETE FROM info WHERE name='"+nam+"'";
       st.executeUpdate(query);
       JOptionPane.showMessageDialog(null,"Delet Successfully");
        }
       catch(Exception ex)
       {
       ex.printStackTrace();
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clas;
    private javax.swing.JLabel day;
    private com.toedter.calendar.JDateChooser doa;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton file;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField path;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sec;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}

  //  @Override
   // public void hyperlinkUpdate(HyperlinkEvent e) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
//}